# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

###########################
# Volume contenant les données (/mnt/sda1/var/....)
#-----> docker volume ls      puis    docker volume inspect 1ec3456ef...
###########################
volumes:
    database_data:
        driver: local

services:
###########################
# Setup the Nginx container
###########################
#    nginx:
#        image: nginx:latest
#        ports:
#            - 7777:80
#        volumes:
#            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#        volumes_from:
#            - php
#
###########################
# Setup the Apache container
###########################
    httpd:
        container_name: dockerapache_httpd_1
        restart: always
        image: httpd:2.4.25
        ports:
            - 80:80
        volumes:
            - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
            #- ./docker/apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
            - ./docker/apache/vhosts/:/usr/local/apache2/conf/vhosts
        volumes_from:
            - php

###########################
# Setup the PHP container
###########################
    php:
        container_name: dockerapache_php_1
        restart: always
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - ./www/:/usr/local/apache2/htdocs
            - ./docker/php/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
            - ./docker/php/php-mail.conf:/usr/local/etc/php/conf.d/mail.ini:ro


###########################
# Setup the Database (MySQL) container
###########################
    mysql:
        container_name: dockerapache_mysql_1
        restart: always
        image: mysql:5.6.36
        ports:
            - 3306:3306
        volumes:
            - database_data:/var/lib/mysql
            - ./docker/mysql/conf-mysql.cnf:/etc/mysql/mysql.conf.d/conf-mysql.cnf:ro
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: BDD_DEV
            MYSQL_USER: gbe
            MYSQL_PASSWORD: gbe
